[build-system]
requires = ["setuptools==80.9.0", "wheel==0.46.2"]
build-backend = "setuptools.build_meta"

[project]
name = "codestra-middleware-connector-sdk"
version = "1.0.0"
description = "Codestra Middleware connector SDK"
requires-python = ">=3.12,<3.14"
dependencies = []

[tool.setuptools.packages.find]
include = ["middleware", "middleware.*"]
